### ISSUE TITLE
Slack parser

### ISSUE THREAD

**Issue by alexanderadam** [opthomas-prime/xmpp-webhook#6] opened 2019-07-24 08:54 UTC
Initially I was looking for [a webhook from gitea to XMPP](https://github.com/go-gitea/gitea/issues/7549) but now I am thinking that it would probably be much smarter if `xmpp-webhook` would get a :tada: **Slack parser** :tada: instead.

There are so many services with Slack webhook integrations (even my [beloved gitea](https://github.com/go-gitea/gitea/blob/master/models/webhook_slack.go)) and I guess it would help the XMPP ecosystem a lot if it would be as easy to integrate stuff as it is in Slack. IMHO it could be even a game changer for some (i.e. [here](https://twitter.com/evilgaywitch/status/549614917267894272)).

My _guess_ is, that at least [the _basic_ API is probably not too bad to implement](https://api.slack.com/incoming-webhooks) (the "fancy" example is probably complicated though).

What do you think?

PS: Again, thank you so much for your work! :+1: 
PPS: the only 'alternative' seems to be an [alpha state Prosody module for the that isn't working anymore](https://hg.prosody.im/prosody-modules/file/284d8c18060e/mod_slack_webhooks/mod_slack_webhooks.lua)

**Comment by opthomas-prime** [comment] 2019-07-29 08:55
Hi Alex,

a Gitea parser function shouldn't be a big deal. I wanted to rework this bridge anyway soon...

The biggest change will be that the recipients can be overridden by GET/POST parameters.

Regarding the Slack parser: I'm not sure if i understand you correctly, but this bridge is designed to receive alerts/messages via HTTP and send them to XMPP recipients only. The link you posted points to the _Incoming_ Webhooks documentation of Slack which would be the 'wrong' direction. _Outgoing_ Webhooks seem to be deprecated: https://api.slack.com/custom-integrations/outgoing-webhooks. I don't use Slack (neither private nor with companies i work with/in), so it's hard for me to evaluate this request right now. Are you willing to invest some time and build a prototype with me (After i understood what we are trying to achieve :smile:)?

As for your request in the other issue: Sure, a Docker image would be useful (Atleast as dev environment). I'll think about that.

**Comment by alexanderadam** [comment] 2019-07-29 10:04
> The link you posted points to the Incoming Webhooks documentation of Slack which would be the 'wrong' direction. 

Maybe I formulated this in a misleading way:

Gitea (and many other projects) often doesn't have native XMPP webhook support. But they have very often Slack support. So people that favour XMPP over Slack won't be able to use them. Usually those Slack webhooks are for posting a message into a channel when an event occurred.
Furthermore applications usually integrate Slack by using the API for **Incoming** Webhooks (because it's incoming from the perspective of the Slack interface).

So if `xmpp-webhook` would be able to parse and interpret the payload that was meant for Slack, it must be able to interpret the JSON hash as described in the incoming API of Slack.
And **if** `xmpp-webook` would be able to interpret the payload*, every service with Slack webhook support would automatically have XMPP webhook support (if `xmpp-webhook` is used).

*I don't think that it would be possible to enable [**every** formatting syntax that Slack supports](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Robert%20DeSoto%20added%20a%20new%20task%22%2C%22attachments%22%3A%5B%7B%22fallback%22%3A%22Plan%20a%20vacation%22%2C%22author_name%22%3A%22Owner%3A%20rdesoto%22%2C%22title%22%3A%22Plan%20a%20vacation%22%2C%22text%22%3A%22I%27ve%20been%20working%20too%20hard%2C%20it%27s%20time%20for%20a%20break.%22%2C%22actions%22%3A%5B%7B%22name%22%3A%22action%22%2C%22type%22%3A%22button%22%2C%22text%22%3A%22Complete%20this%20task%22%2C%22style%22%3A%22%22%2C%22value%22%3A%22complete%22%7D%2C%7B%22name%22%3A%22tags_list%22%2C%22type%22%3A%22select%22%2C%22text%22%3A%22Add%20a%20tag...%22%2C%22data_source%22%3A%22static%22%2C%22options%22%3A%5B%7B%22text%22%3A%22Launch%20Blocking%22%2C%22value%22%3A%22launch-blocking%22%7D%2C%7B%22text%22%3A%22Enhancement%22%2C%22value%22%3A%22enhancement%22%7D%2C%7B%22text%22%3A%22Bug%22%2C%22value%22%3A%22bug%22%7D%5D%7D%5D%7D%5D%7D) but I'm sure that 99% of the services have simple output anyway

**Comment by opthomas-prime** [comment] 2019-07-29 11:33
Okay, now i got it :smile:. Thanks for the explanation. I thought you want to be able to receive/forward messages from a slack channel.... Now it makes sense.
The only problem i can see atm is how we would be able to override the JID's (The feature that doenst exist yet) with the slack endpoint.

**Comment by alexanderadam** [comment] 2019-07-29 12:10
What exactly do you mean by `override the JID's`?

The receiver list is customisable via the environment variable `XMPP_RECEIVERS`, isn't it?

**Comment by opthomas-prime** [comment] 2019-07-29 12:23
Yes, currently this is the only way the receivers are specified. But one of the changes i want to implement (i wanted to spend some time with it tomorrow actually) is, that the receivers can be set in the webhook request's to override the default config from the environment. Since we can't specify the URL/paramters for the slack integration freely (as far as i understood it correctly, i haven't checked the documentaion yet) this won't be possible in the same way as for Grafana/Prometheus...

**Comment by alexanderadam** [comment] 2019-07-29 12:37
Ah I see. I thought about this as well and thought someone could just spin a [second container](https://github.com/opthomas-prime/xmpp-webhook/issues/5) with other credentials.

But you are absolutely right that it would be much better to have just one instance with different configurations.

Not only for Slack but also for Prometheus and Grafana. Because if the container is exposed outside and an attacker knows that such service is running, he could easily flood your MUC with requests. So it would make sense to add a long non guessable path to the URL anyway.

**Comment by opthomas-prime** [comment] 2019-07-29 16:24
@alexanderadam Are you available tomorrow for some input regarding Slack? I got some spare time and will try to make a prototpye for the slack parser...

**Comment by alexanderadam** [comment] 2019-07-29 18:40
I can respond tomorrow afternoon but I'm not a Slack guy either (that's why I want to have this feature). ;)

**Comment by opthomas-prime** [comment] 2020-01-06 17:30
@svensp has kindly built a paerser function for Slack notifications. I just refactored the the feature and would be happy for some feedback!

-> https://github.com/opthomas-prime/xmpp-webhook/tree/slack-handler

@svensp could you verify that the enpoint still works as intended?
@alexanderadam could you have a look at it (test) aswell?

**Comment by opthomas-prime** [comment] 2020-01-26 18:41
I tested the handler using the example request from @svensp (https://github.com/opthomas-prime/xmpp-webhook/blob/master/dev/slack-compatible-notification-example.json) and merged it.

**Comment by opthomas-prime** [comment] 2020-01-26 18:41
(Available in https://github.com/opthomas-prime/xmpp-webhook/releases/tag/0.3)

**Closed by opthomas-prime** 2020-01-26 18:41 UTC
