### ISSUE TITLE
SASL/SCRAM-SHA support using another xmpp lib

### ISSUE THREAD

**Issue by kishorerv93** [opthomas-prime/xmpp-webhook#1] opened 2018-11-08 21:52 UTC
`2018/11/08 21:51:13 Connecting to dr-openfire.lamar.com:5222
2018/11/08 21:51:13 Start TLS
2018/11/08 21:51:13 Authenticating
2018/11/08 21:51:13 no supported SASL mechanism found`

My Openfire config

`

sasl.mechs.00001 | DIGEST-MD5 |   |   |  

sasl.mechs.00002 | SCRAM-SHA-1

`

**Comment by SamWhited** [comment] 2018-11-08 21:58
You need to enable SASL PLAIN auth in Openfire.

**Comment by SamWhited** [comment] 2018-11-11 18:46
@opthomas-prime Sure thing; glad I could be of service. I'm not using this project right this moment, but I was setting up an alertmanager instance and wanted a way to get alerts on my phone without paying for an expensive notifications service so I was looking into using our existing chat service (conversations.im) and started watching this.

If you're interested in adding SCRAM support to the library you use, I have an implementation that I built for another (also XMPP related) project here: https://godoc.org/mellium.im/sasl

**Comment by opthomas-prime** [comment] 2018-11-13 07:18
@SamWhited I'm considering switching the lib anyway. So let's see :smile:

**Comment by opthomas-prime** [comment] 2019-07-29 16:22
I don't think there will be any changes in https://github.com/mattn/go-xmpp tbh. I'll check for other libs tomorrow. IF there are alternatives i'll reopen the issue.

**Comment by SamWhited** [comment] 2019-07-29 16:29
Shameless self promotion: I just did a release of [`mellium.im/xmpp`](https://godoc.org/mellium.im/xmpp) that I think will make the API more or less stable (though it's still not 1.0 and I'm not making any guarantees, it's waiting on some changes to the `encoding/xml` package that may still break things). I'm not sure if it would fit your needs or not (right now it's a bit low-level, I'd like to do a higher-level client package at some point), but I'd be curious to get your feedback on the design and API either way if you evaluate it or have the time to take a look.

The only other maintained XMPP library that I'm aware of is [`gosrc.io/xmpp`](https://godoc.org/gosrc.io/xmpp) in case you want to compare. I believe this one is maintained and owned by ProcessOne (the ejabberd folks).

**Comment by opthomas-prime** [comment] 2019-07-29 16:36
Hey @SamWhited! Thanks for your input. I'll check your lib first. Are you availlable on IRC if i have problems/questions?

**Comment by SamWhited** [comment] 2019-07-29 16:39
@opthomas-prime I can be; I normally don't leave it on, but I'll try to stay logged in even when I'm away from my computer today so I can get back to you. I'm `SamWhited` on Freenode, Mozilla, or GeekShed. Also my JID is the same as my email (`sam@samwhited.com`) if you prefer either of those.

**Comment by opthomas-prime** [comment] 2019-07-29 16:42
@SamWhited Great. I won't be able to check this today. I'll just ping you here if you are not online on freenode Freenode tomorrow!?

**Comment by SamWhited** [comment] 2019-07-29 16:56
@opthomas-prime if you could drop me an email or message me on any XMPP compatible service instead I'd appreciate it. I'll try to remember to log in on IRC tomorrow too though.

**Comment by opthomas-prime** [comment] 2019-07-29 17:17
@SamWhited We'll find a way :D. No need to stay online for this - we got plenty of time...

**Comment by opthomas-prime** [comment] 2019-07-30 11:05
Hi @SamWhited i started to play around with mellium.im/xmpp.
Unfortunately i got some problems (Mainly caused by lacking knowledge with XMPP i guess...).

https://github.com/opthomas-prime/xmpp-webhook/blob/mellium-xmpp/main.go#L21
- The server i'm connecting to has no SRV records, so i had to use a custom dialer (NoLookup: true).
- The server i'm connecting to has only StartTLS enabled (forced) and no dedicated TLS Port, so i had to specify NoTLS: true
I'm not sure if im doing this correctly. This feels kinda wrong. Shouldn't the XMPP lib figure out how to connect to a server? Maybe i was just lucky with our configuration, but github.com/emgee/go-xmpp/src/xmpp 'just worked'.

https://github.com/opthomas-prime/xmpp-webhook/blob/mellium-xmpp/main.go#L74 fails with https://github.com/mellium/xmpp/blob/master/session.go#L360
- 'tok' is 'version='1.0'
- The value doesn't seem to be complete garbage - do you have any hints?

**Comment by SamWhited** [comment] 2019-07-30 14:10
> I'm not sure if im doing this correctly. This feels kinda wrong. Shouldn't the XMPP lib figure out how to connect to a server?

For the most part it does, but you do have to specify no TLS, otherwise it could be subject to downgrade attacks. I suppose I could change things to make setting NoTLS just allow fallback, but that seems like it could be risky and that people would set it without understanding the consequences. I'll have to think about that one.

> The value doesn't seem to be complete garbage - do you have any hints?

I've never seen that before; any chance you can record the stream and send me a copy? This definitely should never be hit so that sounds like a pretty serious bug in either the server or my library (and it's more likely to be my library).

**Comment by SamWhited** [comment] 2019-07-30 14:11
I forgot to mention, if you do have an XMPP account anywhere a handful of us hang out in `golang@conference.samwhited.com`, a Go focused room on my server. You'd be welcome to join us and ask any questions there (or I'm online now so feel free to ping me on IRC).

**Comment by Neustradamus** [comment] 2019-09-04 13:02
Do you know Jackal?
- https://github.com/ortuman/jackal

**Comment by alexanderadam** [comment] 2019-09-04 13:12
@Neustradamus Jackal is a XMPP _server_ and not a _client library_, or am I missing something here?

**Comment by Neustradamus** [comment] 2019-09-04 13:41
Yes it is a XMPP server, it is only an information ^^

**Comment by Neustradamus** [comment] 2019-09-04 15:28
Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by opthomas-prime** [comment] 2019-09-05 06:03
Thanks for the info @Neustradamus. I am currently trying to switch to Sam's XMPP lib (mellium.im/xmpp/). Unfortunately there are some problems with ejabberd and i am not able (time-wise) to support Sam at the moment with the required informations to fix these things. I will have some spare time in the upcoming weekends and will try to sort things out then...

**Comment by Neustradamus** [comment] 2019-09-05 08:11
@opthomas-prime: Yes for @SamWhited lib, it is a good news.
Have you tested Jackal XMPP server?
It must to be a solution to replace your ejabberd?
Not all features yet but maybe good to contrib?
Contact @ortuman, the main dev for more informations...

**Comment by opthomas-prime** [comment] 2019-09-05 09:11
@Neustradamus No, i haven't. We are using ejabberd in the company im working at - there are currently no plans to replace it, since it does a pretty good job. But when the current isses/features in this are done, i'll test the webhook against some servers (Including Jackal).

**Comment by opthomas-prime** [comment] 2019-10-30 18:04
I decided that we have to switch to Prosody at our company. I wasn't able to track down the problem with Sam's XMPP lib and our Ejabberd Version/Environment completely - so i'm trying to be pragmatic :smile:...
I'm going to work on the required steps to switch to Sam's lib in the coming days...

**Comment by opthomas-prime** [comment] 2019-11-02 09:21
@kishorerv93 SASL/SCRAM should work now in https://github.com/opthomas-prime/xmpp-webhook/tree/mellium-xmpp. It would be great if you guys (If you are actually using this tool) could test if the connection/discovery with your Jabber-Server is still working correctly...

**Comment by opthomas-prime** [comment] 2019-11-04 20:12
Fiex with https://github.com/opthomas-prime/xmpp-webhook/pull/11

**Comment by Neustradamus** [comment] 2019-11-05 02:28
Thanks for your changes!

Now it works for SCRAM-SHA-1 + SCRAM-SHA-1-PLUS + SCRAM-SHA-256 + SCRAM-SHA-256-PLUS and other?

**Comment by opthomas-prime** [comment] 2019-11-06 18:43
It now supports: SASL PLAIN, SCRAM-SHA-1 and SCRAM-SHA-1-PLUS

**Comment by alexanderadam** [comment] 2019-11-07 11:28
@Neustradamus to be more specific: it supports exactly the same things that [mellium/xmpp](https://github.com/mellium/xmpp/) supports.
So this means if you are missing something, it should be handled in [the dedicated issue tracker](https://github.com/mellium/xmpp/issues) of the library.

**Comment by Neustradamus** [comment] 2019-11-07 13:51
@SamWhited, mellium/xmpp does not support SCRAM-SHA-256 and SCRAM-SHA-256-PLUS?

**Comment by SamWhited** [comment] 2019-11-07 15:54
@Neustradamus it supports whatever you want to write using it, but those are also builtin. See the list of [`Mechanism`]'s.

[`Mechanism`]: https://godoc.org/mellium.im/sasl#Mechanism

**Comment by opthomas-prime** [comment] 2019-11-07 18:43
Hi @Neustradamus, @SamWhited and @alexanderadam. This is indeed a configuration on my side. I totally missed, that SCRAM-SHA-256 and SCRAM-SHA-256-PLUS is supported by https://github.com/mellium/xmpp/ aswell. I'll text and fix that ASAP!

**Comment by SamWhited** [comment] 2019-11-07 18:44
It's not really a big deal either way, very few people support SCRAM-SHA-256, and those that do also likely support SHA-1, but thanks for looking into it :)

**Comment by opthomas-prime** [comment] 2019-11-07 18:54
I want to get the best out of your lib @SamWhited :smile:, so thanks for the hint. Is anyone able to test SCRAM-SHA-256 if i add it to the supported methods?

**Comment by opthomas-prime** [comment] 2020-01-05 12:44
(Finally/Hopefully) fixed with https://github.com/opthomas-prime/xmpp-webhook/commit/d4329d060be3f9cd17ed0a44c0f2dead477c2951

**Closed by opthomas-prime** 2020-01-05 12:44 UTC

**Comment by Neustradamus** [comment] 2020-01-05 13:06
@opthomas-prime: Thanks!
Are you sure about the order?
It must be 256-PLUS>256>1-PLUS>1>PLAIN, no?

**Comment by opthomas-prime** [comment] 2020-01-05 13:12
You are right, my bad. I changed and amended it...
